# Generated by Django 2.1.5 on 2020-05-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('geoname_id', models.IntegerField()),
                ('state', models.CharField(default='', max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
