# Generated by Django 2.1.5 on 2020-05-20 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20200520_0747'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City2',
            new_name='City',
        ),
    ]
